readme:
	@echo  generate PDF with Refs
	Xelatex *.tex 
	Xelatex *.tex
	Xelatex *.tex
	@echo delete temp files after the generating work done
	rm *.bib *.blg *.bbl *.aux *.log *.brf *.nlo *.out *.dvi *.ps *.lof *.toc \
		*.fls *.fdb_latexmk *.pdfsync *.synctex*.gz *.ind *.ilg *.idx

clean:
	rm *.bib *.blg *.bbl *.aux *.log *.brf *.nlo *.out *.dvi *.ps *.lof *.toc \
		*.fls *.fdb_latexmk *.pdfsync *.synctex*.gz *.ind *.ilg *.idx
